# Generated by Django 5.2.4 on 2025-08-23 15:51

import django.db.models.deletion
import orders.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_name', models.CharField(max_length=50)),
                ('print_type', models.CharField(choices=[('laser', '레이저 각인'), ('color', '컬러 인쇄')], max_length=20)),
                ('print_state', models.CharField(choices=[('preparing', '시안 확인중'), ('pending', '인쇄 대기'), ('printed', '인쇄 완료')], max_length=20)),
                ('print_image', models.ImageField(upload_to=orders.utils.printUploadPath)),
                ('print_design', models.FileField(upload_to=orders.utils.printUploadPath)),
            ],
        ),
        migrations.CreateModel(
            name='PrintItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('print_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_items', to='orders.printinfo')),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productoption')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_type', models.CharField(choices=[('courier', '택배'), ('quick', '퀵/화물'), ('deliver', '직배송'), ('pickup', '방문수령'), ('none', '배송없음')], max_length=10)),
                ('shipper_name', models.CharField(max_length=50)),
                ('shipper_contact', models.CharField(blank=True, max_length=12)),
                ('shipper_contact_alt', models.CharField(blank=True, max_length=12)),
                ('shipper_address', models.CharField(blank=True, max_length=300)),
                ('receiver_name', models.CharField(max_length=30)),
                ('receiver_contact', models.CharField(max_length=12)),
                ('receiver_contact_alt', models.CharField(blank=True, max_length=12)),
                ('receiver_address', models.CharField(max_length=300)),
                ('receiver_message', models.CharField(blank=True, max_length=100)),
                ('shipment_fee', models.PositiveSmallIntegerField(default=3000)),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='partners.company')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('order_state', models.CharField(choices=[('pending', '결제대기'), ('paid', '결제완료'), ('preparing', '배송준비중'), ('shipped', '처리완료')], max_length=20)),
                ('buyer_name', models.CharField(blank=True, max_length=20)),
                ('purchase_type', models.CharField(choices=[('credit', '신용거래'), ('deposit', '무통장')], default='신용거래', max_length=20)),
                ('purchase_state', models.CharField(choices=[('pending', '입금 대기'), ('receivable', '미수금'), ('paid', '결제완료')], default='입금 대기', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_orders', to='partners.company')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='partners.channel')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='partners.company')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_orders', to='orders.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=12)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.courier')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='orders.shipment')),
            ],
        ),
    ]
