# Generated by Django 5.2.4 on 2025-08-23 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='partners.courier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='purchased_orders', to='partners.company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='orders', to='partners.channel'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sales_orders', to='partners.company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shipping_orders', to='orders.shipment'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='shipments', to='partners.company'),
        ),
    ]
