# Generated by Django 5.2.4 on 2025-08-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_state',
            field=models.CharField(choices=[('pending', '입금 대기'), ('receivable', '미수금'), ('paid', '결제완료')], default='입금 대기', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='purchase_type',
            field=models.CharField(choices=[('credit', '신용거래'), ('deposit', '무통장')], default='신용거래', max_length=20),
        ),
    ]
