# Generated by Django 5.2.4 on 2025-08-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('excel_file_name', models.CharField(blank=True, max_length=100)),
                ('excel_sheet_num', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('excel_start_row', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('order_id_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('product_name_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('product_option_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('product_code_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quantity_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_price_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ordered_at_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('buyer_name_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('buyer_contact_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('buyer_message_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('receiver_name_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('receiver_contact_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('receiver_contact_alt_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('receiver_zip_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('receiver_address_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('receiver_message_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('invoice_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fee_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('s_order_id_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('s_invoice_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('s_courier_column', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(blank=True, max_length=12)),
                ('biz_reg_num', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(max_length=20, unique=True)),
                ('tracker_url', models.URLField()),
                ('key_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('invoice_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sender_name_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sender_contact_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sender_address_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('receiver_name_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('receiver_contact_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('receiver_contact_alt_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('receiver_address_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('receiver_message_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shipment_key_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('product_name_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('product_quantity_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('box_count_column', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
