# Generated by Django 5.2.4 on 2025-08-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField()),
                ('user_id', models.CharField()),
                ('user_pw', models.CharField()),
            ],
        ),
    ]
