# Generated by Django 5.2.4 on 2025-08-13 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_alias', models.CharField(max_length=20)),
                ('use_options', models.BooleanField(default=False)),
                ('use_phone_models', models.BooleanField(default=False)),
                ('option1', models.CharField(blank=True, max_length=50, null=True)),
                ('option2', models.CharField(blank=True, max_length=50, null=True)),
                ('option3', models.CharField(blank=True, max_length=50, null=True)),
                ('thumbnail', models.ImageField(upload_to='products/thumbnails/')),
                ('thumbnail_hover', models.ImageField(blank=True, null=True, upload_to='products/thumbnails/')),
                ('detail_image', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_link', models.URLField(blank=True, null=True)),
                ('engravable', models.BooleanField(default=False)),
                ('printable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '상품 목록',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('galaxy', '갤럭시'), ('iPhone', '아이폰')], max_length=10)),
                ('model_name', models.CharField(max_length=50)),
                ('model_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'ordering': ['model_type', 'model_name'],
                'unique_together': {('model_type', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='product/thumbnails/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(blank=True, max_length=20, null=True)),
                ('option2', models.CharField(blank=True, max_length=20, null=True)),
                ('option3', models.CharField(blank=True, max_length=20, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('inbound_price', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('phone_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.phonemodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.product')),
            ],
            options={
                'verbose_name': '옵션',
                'verbose_name_plural': '옵션 목록',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.producttag'),
        ),
    ]
