# Generated by Django 5.2.4 on 2025-08-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='phonemodel',
            constraint=models.UniqueConstraint(condition=models.Q(('model_number', ''), _negated=True), fields=('model_number',), name='unique_code_when_not_blank'),
        ),
    ]
