# Generated by Django 5.2.4 on 2025-08-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_phonemodel_unique_code_when_not_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to='media/products/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_hover',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to='media/product/thumbnails/'),
        ),
    ]
