# Generated by Django 5.2.4 on 2025-08-24 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='compatiblephonemodel',
            name='unique_product_phone_model',
        ),
        migrations.RemoveField(
            model_name='compatiblephonemodel',
            name='product_phone_model_option',
        ),
        migrations.AddField(
            model_name='compatiblephonemodel',
            name='phone_model_option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phone_models', to='products.productphonemodeloption'),
            preserve_default=False,
        ),
    ]
